### ISSUE TITLE
desktop/exwm folder and files

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/dots#1]
Do the desktop/exwm folder and files go in the ./emacs.d/modules/ folder or somewhere else? 
Many thanks in advance!

**Comment by jethrokuan** [comment]
They remain in `.doom.d/modules`. Doom Emacs seems to pick them up modules from that path as well.

**Comment by anthrolisp** [comment]
I kept getting the following error. Any ideas?
`Debugger entered--Lisp error: (file-missing "Opening directory" "No such file or directory" "/home/justin/Dropbox/org/gtd")
  directory-files("~/Dropbox/org/gtd/" nil nil t)
  find-lisp-find-files-internal("~/Dropbox/org/gtd/" find-lisp-default-file-predicate find-lisp-default-directory-predicate)
  find-lisp-find-files("~/Dropbox/org/gtd/" ".org$")
  (setq org-agenda-files (find-lisp-find-files jethro/org-agenda-directory ".org$"))
  (progn (defalias (quote jethro/org-archive-done-tasks) (function (lambda nil "Archive all done tasks." (interactive) (org-map-entries (quote org-archive-subtree) "/DONE" (quote file))))) (require (quote find-lisp)) (setq jethro/org-agenda-directory "~/Dropbox/org/gtd/") (setq org-agenda-files (find-lisp-find-files jethro/org-agenda-directory ".org$")))
  (if (featurep (quote org)) (progn (defalias (quote jethro/org-archive-done-tasks) (function (lambda nil "Archive all done tasks." (interactive) (org-map-entries (quote org-archive-subtree) "/DONE" (quote file))))) (require (quote find-lisp)) (setq jethro/org-agenda-directory "~/Dropbox/org/gtd/") (setq org-agenda-files (find-lisp-find-files jethro/org-agenda-directory ".org$"))) (eval-after-load (quote org) (function (lambda nil (progn (defalias (quote jethro/org-archive-done-tasks) (function (lambda nil "Archive all done tasks." ... ...))) (require (quote find-lisp)) (setq jethro/org-agenda-directory "~/Dropbox/org/gtd/") (setq org-agenda-files (find-lisp-find-files jethro/org-agenda-directory ".org$")))))))
  eval-buffer(#<buffer  *load*-230642> nil "/home/justin/.doom.d/config.el" nil t)  ; Reading at buffer position 9371
  load-with-code-conversion("/home/justin/.doom.d/config.el" "/home/justin/.doom.d/config.el" t t)
  load("/home/justin/.doom.d/config" t nomessage)
  (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage)))
  (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((not ...) (cons ... ...)) ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (if doom-interactive-mode (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let ... ...))) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))
  (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if doom-interactive-mode (progn (if doom-modules (progn (maphash (function (lambda ... ...)) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))))
  (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" doom-private-dir))) (err (cond (... ...) (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let ... ...))) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if doom-interactive-mode (progn (if doom-modules (progn (maphash (function ...) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* (... ...) (signal ... ...))))))))
  (progn (setq doom-init-modules-p t doom-modules nil) (load custom-file (quote noerror) (quote nomessage)) (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e))))) (progn (if doom-modules (progn (maphash (function (lambda ... ...)) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if doom-interactive-mode (progn (if doom-modules (progn (maphash ... doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...))))))))
  (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-p t doom-modules nil) (load custom-file (quote noerror) (quote nomessage)) (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))) (progn (if doom-modules (progn (maphash (function ...) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if doom-interactive-mode (progn (if doom-modules (progn ...)) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let ... ...) (... ...) (... ...))))))))
  doom-initialize-modules()
  (if noninteractive (doom-initialize-packages) (doom-initialize-core) (doom-initialize-modules))
  eval-buffer(#<buffer  *load*> nil "/home/justin/.emacs.d/init.el" nil t)  ; Reading at buffer position 2724
  load-with-code-conversion("/home/justin/.emacs.d/init.el" "/home/name/.emacs.d/init.el" t t)
  load("/home/justin/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1e0f5d>)()
  command-line()
  normal-top-level()
`

**Comment by anthrolisp** [comment]
Thank you!
