### ISSUE TITLE
org capcture

### ISSUE THREAD

**Issue by xukeek** [jethrokuan/dots#2]
Hi, I got a error 'wrong type argument stringp nil' when i use org capcture,

**Comment by jethrokuan** [comment]
which template?

**Comment by xukeek** [comment]
inbox

**Comment by jethrokuan** [comment]
I've been using it daily without issues, could you toggle debug on error and paste the backtrace here.

**Comment by xukeek** [comment]
Debugger entered--Lisp error: (error "Capture abort: Wrong type argument: stringp, nil")
  signal(error ("Capture abort: Wrong type argument: stringp, nil"))
  error("Capture abort: %s" "Wrong type argument: stringp, nil")
  org-capture(nil)
  funcall-interactively(org-capture nil)
  call-interactively(org-capture record nil)
  command-execute(org-capture record)
  counsel-M-x-action("org-capture")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "org-capture" "jethro/org-process-inbox" "org-agenda" "R" "cd" "5x5" "SAS" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "wos" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "pass" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" ...) :predicate #f(compiled-function (x) #<bytecode 0x43f3c9bd>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by jethrokuan** [comment]
no idea, you probably copied it wrong somewhere.
