### ISSUE TITLE
org-download when dragging an image from the local file system

### ISSUE THREAD

**Issue by vonpupp** [jethrokuan/dots#4]
Hello,

Congratulations on org-roam! I am using it but still learning. I was using your [org-download section] and it used to work fine, when I dragged an image, it created a folder named "images" within a folder with the same name of the org roam document which was exactly what I was looking for. For some unknown reason (possibly an update to doom emacs), now when I try to do the same, emacs "opens" the image instead of including it within the document as a link.

The error that I get is: Error: "(error Autoloading file /home/av/.emacs.d.doomemacs/.local/straight/build-27.2/org-download/org-download.elc failed to define function +org-dragndrop-download-dnd-fn)", when I don't have the dragndrop feature enabled in the init.el file. On the other hand, when I do have the dragndrop feature enabled in the init.el, I get the error: Error: (void-function +org-dragndrop-download-dnd-fn).

I am unsure how to proceed to enable that exact feature that was working like a charm before. I wonder if it is still working for you on the latest version of Doom emacs (develop branch)? Thanks in advance.

[org-download section]: https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el#L405

**Comment by jethrokuan** [comment]
Hi,

Thanks! I don't actually know how that used to work before, `+org-dragndrop-download-dnd-fn` was probably something in Doom Emacs that existed and now it does not. It looks like Doom has replaced it back with `org-download-dnd`, so it's probably safe to replace all occurrences of it with `org-download-dnd`.

**Comment by vonpupp** [comment]
Thank you very much @jethrokuan!

That works, however when I restart emacs and open the org roam file the images are not displayed inline. All I get is text like this:
"[[download:<path to org-roam>/images/<slug>/file.png]]"

It seems to be related to [this issue]. Also it seems that the [dragndrop.el file] sets up a "download" handler. But I am not experienced in emacs and furthermore I just moved from spacemacs to doom, so I am working on my config to make it to work little by little.

Yours do work properly? I don't remember the prefix "download" to exist in the past.

[this issue]: https://github.com/hlissner/doom-emacs/issues/2539
[dragndrop.el file]: https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/dragndrop.el#L20

**Comment by jethrokuan** [comment]
> Yours do work properly? I don't remember the prefix "download" to exist in the past.

This is a Doom invention, I don't use the `+dragndrop` flag in my config.
