### ISSUE TITLE
Don't you use auctex in your Emcas for LaTeX configuartions?

### ISSUE THREAD

**Issue by hongyi-zhao** [jethrokuan/dots#5]
I noticed your blog [comments](https://blog.jethro.dev/posts/migrating_to_doom_emacs/) on the configuration of an LaTeX editing environment based on Doom Emacs. But it seems that you don't use `auctex` at all.

Any hints for this selection?

Regards,
HY

**Comment by jethrokuan** [comment]
I practically don't need to configure anything for latex, the Doom emacs `latex` layer is more than sufficient, and it uses auctex: https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/latex/packages.el#L4

**Comment by hongyi-zhao** [comment]
Thank you for your information.

I am in the same predicament as you: I've tried for several days to deploy an Emacs based LaTeX environment, but still can't achieve the ideal result, especially I can't figure out a working [lsp-mode](https://github.com/emacs-lsp/lsp-mode) based IDE-like configuration out of Emacs. I have to admit that Emacs is too powerful and complicated, while my level of knowledge is really low in this field.

So the existent Emacs frameworks, such as [doom-emacs](https://github.com/hlissner/doom-emacs) and [spacemacs](https://github.com/syl20bnr/spacemacs) enter my consideration. It is in this context that I found your above blog post with the help of google.

I've a cursory glimpse on them, and it seems that spacemacs has more users and preconfigured functions. So, I still can't decide which one I should choose.

**Comment by jethrokuan** [comment]
My personal view is that Doom Emacs is better maintained, faster and nicer to work with (like adding customizations), but you can give both a try and see which you prefer.

**Comment by hongyi-zhao** [comment]
> Doom Emacs is better maintained

The latest commit of [doom](https://github.com/hlissner/doom-emacs/commit/2731685095d1e6101b3215aa689426e1834ce00f) happened 9 days ago, while the latest commit of [spacemacs](https://github.com/syl20bnr/spacemacs/commit/ab6b165e964ad9b731b1a0b80f3ed419d67694a2) happened 10 hours ago.

As far as LaTeX is concerned, it seems that [lsp based configuration](https://develop.spacemacs.org/layers/+lang/latex/README.html#lsp) is only supplied in spacemacs.

Fortunately, based on the wonderful notes [here](https://tam5917.hatenablog.com/entry/2021/04/01/014719), I tried out a working vanilla Emacs based solution using `auctex`, `eglot`, `texlab`, and `company`, see [here](https://github.com/astoff/digestif/issues/33#issuecomment-863134170) for more detailed info. So, at least from the current point of view, I can postpone the switch to other Emacs frameworks.
